"""initial"""
from alembic import op
import sqlalchemy as sa

revision = 'ae54dbc89ba9'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('session_epoch', sa.Integer(), nullable=False),
    sa.Column('sync_seq', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admin_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('csrf', sa.String(length=64), nullable=False),
    sa.Column('expires', sa.BigInteger(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mime', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_owner_id'), 'attachments', ['owner_id'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('pair_key', sa.String(length=73), nullable=False),
    sa.Column('a', sa.String(length=36), nullable=False),
    sa.Column('b', sa.String(length=36), nullable=False),
    sa.Column('requester', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['b'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester'], ['users.id'], ),
    sa.PrimaryKeyConstraint('pair_key')
    )
    op.create_index(op.f('ix_contacts_a'), 'contacts', ['a'], unique=False)
    op.create_index(op.f('ix_contacts_b'), 'contacts', ['b'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pair_key', sa.String(length=73), nullable=False),
    sa.Column('a', sa.String(length=36), nullable=False),
    sa.Column('b', sa.String(length=36), nullable=False),
    sa.Column('next_seq', sa.BigInteger(), nullable=False),
    sa.Column('a_read', sa.BigInteger(), nullable=False),
    sa.Column('b_read', sa.BigInteger(), nullable=False),
    sa.Column('a_clear', sa.BigInteger(), nullable=False),
    sa.Column('b_clear', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['b'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair_key')
    )
    op.create_index(op.f('ix_conversations_a'), 'conversations', ['a'], unique=False)
    op.create_index(op.f('ix_conversations_b'), 'conversations', ['b'], unique=False)
    op.create_table('mobile_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('access_hash', sa.String(length=64), nullable=False),
    sa.Column('refresh_hash', sa.String(length=64), nullable=False),
    sa.Column('access_expires', sa.BigInteger(), nullable=False),
    sa.Column('refresh_expires', sa.BigInteger(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_hash'),
    sa.UniqueConstraint('refresh_hash'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('sync_events',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'seq')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('attachment_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'seq'),
    sa.UniqueConstraint('sender_id', 'client_id')
    )
    op.create_index('ix_message_history', 'messages', ['conversation_id', 'seq'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_history', table_name='messages')
    op.drop_table('messages')
    op.drop_table('sync_events')
    op.drop_table('mobile_sessions')
    op.drop_index(op.f('ix_conversations_b'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_a'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_contacts_b'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_a'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('audits')
    op.drop_index(op.f('ix_attachments_owner_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('admin_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
